"""Emit numbers.tex: every headline number in the paper as a LaTeX macro,
sourced from paper2_data/. Placeholders (\\pending) for metrics whose runs
have not finished yet — rerun after aggregation to finalize.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def jload(name):
    p = os.path.join(ROOT, "paper2_data", name)
    return json.load(open(p)) if os.path.exists(p) else None


def pct(x, nd=1):
    return f"{100 * x:.{nd}f}\\%" if x is not None else "\\pending{}"


def get(d, *ks):
    for k in ks:
        if d is None:
            return None
        d = d.get(k)
    return d


def sv(name, *ks):
    v = get(SV, name, *ks)
    if isinstance(v, dict):
        return v
    return None


def pm(stat, nd=1):
    """mean (min–max) formatting from an agg dict."""
    if not stat:
        return "\\pending{}"
    m, lo, hi = stat["mean"], stat["min"], stat["max"]
    if stat["n_seeds"] == 1:
        return f"{100*m:.{nd}f}\\%"
    return f"{100*m:.{nd}f}\\% ({100*lo:.{nd}f}--{100*hi:.{nd}f})"


SV = jload("seed_variance.json")
s24 = jload("domain1_slide24.json")
s8 = jload("domain1_slide8.json")
mz = jload("domain2_maze.json")
sk = jload("domain3_sokoban.json")
pd_ = jload("domain4_pendulum.json")
g2 = jload("domain5_2048.json")

L = []
A = L.append
A("% auto-generated by gen_numbers.py — do not edit")
A("\\newcommand{\\pending}{\\textcolor{gray}{--}}")
# domain 1
A(f"\\newcommand{{\\slideDNrate}}{{{pct(get(s24,'denoise','total_rate'))}}}")
A(f"\\newcommand{{\\slideDVrate}}{{{pct(get(s24,'davi','total_rate'))}}}")
A(f"\\newcommand{{\\slideDNgreedy}}{{{pct(get(s24,'denoise','greedy_rate'))}}}")
A(f"\\newcommand{{\\slideEightDNmq}}{{{pct(get(s8,'denoise','move_quality'))}}}")
A(f"\\newcommand{{\\slideEightDVmq}}{{{pct(get(s8,'davi','move_quality'))}}}")
A(f"\\newcommand{{\\slideEightAgg}}{{{pm(sv('slide3','denoise','greedy_all_states'))}}}")
A(f"\\newcommand{{\\slideEightAggDV}}{{{pm(sv('slide3','davi','greedy_all_states'))}}}")
# domain 2
A(f"\\newcommand{{\\mazeDN}}{{{pm(sv('maze','denoise','solve_rate')) if SV else pct(get(mz,'denoise','solve_rate'))}}}")
A(f"\\newcommand{{\\mazeDV}}{{{pm(sv('maze','davi','solve_rate')) if SV else pct(get(mz,'davi','solve_rate'))}}}")
# domain 3
A(f"\\newcommand{{\\sokoDN}}{{{pm(sv('sokoban','denoise','solve_rate_depth60')) if SV else pct(get(sk,'denoise','depth_60','solve_rate'))}}}")
A(f"\\newcommand{{\\sokoDV}}{{{pm(sv('sokoban','davi','solve_rate_depth60')) if SV else pct(get(sk,'davi','depth_60','solve_rate'))}}}")
A(f"\\newcommand{{\\sokoHY}}{{{pct(get(sk,'hybrid_denoise_proposes_value_scores','depth_60','solve_rate'))}}}")
# domain 4
A(f"\\newcommand{{\\pendMSE}}{{{pm(sv('pendulum','denoise_mse','swingup_rate')) if SV else pct(get(pd_,'denoise_mse_regression','swingup_rate'),0)}}}")
A(f"\\newcommand{{\\pendDISC}}{{{pm(sv('pendulum','denoise_disc','swingup_rate')) if SV else pct(get(pd_,'denoise_categorical_21bins','swingup_rate'),0)}}}")
A(f"\\newcommand{{\\pendVAL}}{{{pm(sv('pendulum','value','swingup_rate')) if SV else pct(get(pd_,'value_baseline_lookahead','swingup_rate'),0)}}}")
# domain 5
A(f"\\newcommand{{\\gDN}}{{{pm(sv('g2048','denoiser_reach256')) if SV else pct(get(g2,'denoiser','reach_256'))}}}")
A(f"\\newcommand{{\\gRAND}}{{{pct(get(g2,'random','reach_256'))}}}")
A(f"\\newcommand{{\\gHEUR}}{{{pct(get(g2,'greedy_merge','reach_256'))}}}")
# domains 6-10 (from seed_variance only)
A(f"\\newcommand{{\\hanoiDN}}{{{pm(sv('hanoi','denoise','greedy_all_states'))}}}")
A(f"\\newcommand{{\\hanoiDV}}{{{pm(sv('hanoi','davi','greedy_all_states'))}}}")
A(f"\\newcommand{{\\pomdpDN}}{{{pm(sv('pomdp_maze','denoise','solve_rate'))}}}")
A(f"\\newcommand{{\\pomdpDV}}{{{pm(sv('pomdp_maze','davi','solve_rate'))}}}")
A(f"\\newcommand{{\\loDN}}{{{pm(sv('lightsout','denoise','solve_rate'))}}}")
A(f"\\newcommand{{\\loDV}}{{{pm(sv('lightsout','davi','solve_rate'))}}}")
A(f"\\newcommand{{\\mcDN}}{{{pm(sv('mountaincar','denoise','reach_rate'))}}}")
A(f"\\newcommand{{\\mcVAL}}{{{pm(sv('mountaincar','value','reach_rate'))}}}")
A(f"\\newcommand{{\\pegDN}}{{{pm(sv('pegs','denoise','solve_rate_depth25'))}}}")
A(f"\\newcommand{{\\pegDV}}{{{pm(sv('pegs','davi','solve_rate_depth25'))}}}")

with open(os.path.join(HERE, "numbers.tex"), "w") as f:
    f.write("\n".join(L) + "\n")
print("wrote numbers.tex")
for line in L[2:]:
    print(" ", line)
